#!/usr/bin/env python3

import argparse
from collections import deque
import re
import socket
import ssl
from html.parser import HTMLParser
import urllib.parse

DEFAULT_SERVER = "fakebook.khoury.northeastern.edu"
DEFAULT_PORT = 443

class LinkParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []

    def handle_starttag(self, tag, attrs):
        if tag == 'a':
            for attr, value in attrs:
                if attr == 'href' and value.startswith("/fakebook"):
                    self.links.append(value)

'''
Main class that represents a web crawler.
'''
class Crawler:
    def __init__(self, args):
        self.server = args.server
        self.port = args.port
        self.username = args.username
        self.password = args.password
        self.csrf_token = None
        self.cookie = None
        self.session_id = None
        self.visited_links = set() # used to avoid duplicates
        self.queue = deque() # used to implement breadth-first search
        self.secret_flags = set()

    def send_request(self, path, method="GET", body=None, headers={}):
        # build the request
        request = f"{method} {path} HTTP/1.1\r\n"
        request += f"Host: {self.server}\r\n"
        request += "User-Agent: MyCrawler/1.0\r\n"
        request += "Connection: close\r\n"

        # add components of the request body data
        if body:
            headers["Content-Length"] = str(len(body))
            headers["Content-Type"] = "application/x-www-form-urlencoded"

        # add headers to the request
        for header, value in headers.items():
            request += f"{header}: {value}\r\n"

        request += "\r\n"

        if body:
            request += body

        # create a socket and send the request
        context = ssl.create_default_context()
        with socket.create_connection((self.server, self.port)) as sock:
            with context.wrap_socket(sock, server_hostname=self.server) as ssock:
                print("Request to %s:%d" % (self.server, self.port))
                print(request)
                ssock.sendall(request.encode('ascii'))

                # receive the response
                response = b""
                while True:
                    data = ssock.recv(4096)
                    if not data:
                        break
                    response += data

        # split header and body
        response_headers, response_body = response.split(b"\r\n\r\n", 1)
        headers_text = response_headers.decode()

        # extract the status code
        status_code = headers_text.split("\r\n")[0]
        if '503' in status_code:
            return self.send_request(path, method, body, headers)

        return headers_text, response_body.decode()

    """Helper function to extract the CSRF token from the login page."""
    def extract_csrf_token(self, html):
        start_index = html.find('name="csrfmiddlewaretoken" value="')
        
        if start_index == -1:
            return None

        start_index += len('name="csrfmiddlewaretoken" value="')
        end_index = html.find('"', start_index)
        token = html[start_index:end_index]
        return token
    
    def get_csrf_token(self):
        headers_text, html = self.send_request("/accounts/login/")
        print("LOGIN GET STATUS:", headers_text.split("\r\n")[0])
        print("CSRF TOKEN:", self.csrf_token)
        print("COOKIE:", self.cookie)

        if headers_text is None or html is None:
            return None

        self.csrf_token = self.extract_csrf_token(html)

        # get csrf token from Set-Cookie header using regex
        match = re.search(r"csrftoken=([a-zA-Z0-9]+)", headers_text)
        if match: 
            self.cookie = match.group(1)

    '''
    Method that sends a POST request to the login form page with the username and password
    and obtains a new cookie and the session id
    '''
    def login(self):
        post_data = urllib.parse.urlencode({
            "username": self.username,
            "password": self.password,
            "csrfmiddlewaretoken": self.csrf_token
        })

        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "Referrer": f"https://{self.server}:{self.port}/accounts/login/?next=/fakebook/",
            "Cookie": f"csrftoken={self.cookie}",
            "Origin": f"https://{self.server}"
        }

        headers_text, response_body = self.send_request("/accounts/login/?next=/fakebook/", method="POST", body=post_data, headers=headers)

        match = re.search(r"csrftoken=([a-zA-Z0-9]+)", headers_text)
        if match: # If found, replace the old value in the instance variable
            self.cookie = match.group(1)

        # Using regex, search for string literal "sessionid=" and use ([a-zA-Z0-9]+) to get alphanumeric results
        match = re.search(r"sessionid=([a-zA-Z0-9]+)", headers_text)
        if match: # If found, store it in the instance variable
            self.session_id = match.group(1)
        print("headers text", headers_text)
        

    def crawl(self, link):
        post_body = urllib.parse.urlencode({
            "csrfmiddlewaretoken": self.csrf_token
        })

        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "Cookie": f"csrftoken={self.cookie}; sessionid={self.session_id}",
        }

        headers, body = self.send_request(link, headers=headers)

        # find the secret flag in the body of the response
        flags = re.findall(r"<h3 class='secret_flag' style=\"color:red\">FLAG: ([a-zA-Z0-9]{64})</h3>", body)
        for flag in flags:
            self.secret_flags.add(flag)

        # parse the body of the response to find new links to crawl
        parser = LinkParser()
        parser.feed(body)

        for link in parser.links:
            if link not in self.visited_links:
                self.queue.append(link)
                self.visited_links.add(link)

    # def run(self):
    #     request = "GET / HTTP/1.0\r\n\r\n"

    #     print("Request to %s:%d" % (self.server, self.port))
    #     print(request)
    #     mysocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    #     mysocket.connect((self.server, self.port))
    #     mysocket.send(request.encode('ascii'))

    #     data = mysocket.recv(1000)
    #     # if length of data is zero, the server has closed the connection
    #     if len(data) == 0:
    #         print("Response:\nSocket closed by %s" % self.server)
    #     else:
    #         print("Response:\n%s" % data.decode('ascii'))

    def run(self):
        # extract the CSRF token from the login page
        self.get_csrf_token()

        # log in to the server to obtain a new cookie and session id
        self.login()

        # add /fakebook/ to the queue to start crawling
        self.queue.append("/fakebook/")
        self.visited_links.add("/fakebook/")

        # keep crawling until there are no more links in the queue
        while self.queue and len(self.secret_flags) < 5:
            link = self.queue.popleft()
            self.crawl(link)

        # once all flags have been found, print them out
        print("Secret flags found:")
        for flag in self.secret_flags:
            print("FLAG: ", flag)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='crawl Fakebook')
    parser.add_argument('-s', dest="server", type=str, default=DEFAULT_SERVER, help="The server to crawl")
    parser.add_argument('-p', dest="port", type=int, default=DEFAULT_PORT, help="The port to use")
    parser.add_argument('username', type=str, help="The username to use")
    parser.add_argument('password', type=str, help="The password to use")
    args = parser.parse_args()
    sender = Crawler(args)
    sender.run()
